server:
  port: 8082
  servlet:
    context-path: /banking-service

spring:
  application:
    name: banking-service
  
  # Database configuration for Docker environment
  datasource:
    url: jdbc:postgresql://postgres:5432/microbank
    username: microbank
    password: microbank123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Enable Flyway for Docker environment
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Client Service Integration
client:
  service:
    url: http://client-service:8081/client-service
    timeout: 5000

# AWS SQS Configuration (for async blacklisting)
aws:
  sqs:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    queue:
      blacklist-events: client-blacklist-events

logging:
  level:
    com.microbank.bankingservice: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# JWT Configuration
jwt:
  secret: microbank-jwt-secret-key-2024-very-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

# Security
security:
  jwt:
    secret: microbank-jwt-secret-key-2024-very-long-and-secure
    expiration: 86400000
