server:
  port: 8081

spring:
  application:
    name: client-service
  
  # Database configuration for local PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/microbank?currentSchema=client_schema
    username: postgres
    password: password@001
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: client_schema
  
  # Enable Flyway for local development
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    schemas: client_schema
    default-schema: client_schema

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Logging
logging:
  level:
    com.microbank.clientservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
jwt:
  secret: microbank-jwt-secret-key-2024-very-long-and-secure-for-hs512-algorithm-64bytes
  expiration: 86400000 # 24 hours in milliseconds

# Security
security:
  jwt:
    secret: microbank-jwt-secret-key-2024-very-long-and-secure-for-hs512-algorithm-64bytes
    expiration: 86400000
